const { Customer, User } = require("../models");

const customerData = [
  {
    name: "The Design Booth, LLC",
    email: "lovethedesignbooth@gmail.com",
    phone: "+1 919-610-7510",
    address: "1234 Main St, Raleigh, NC 27601",
    notes: "This is a sample customer generated by the seeder",
  },
  {
    name: "Pricode",
    email: "info@pricode.io",
    phone: "+1 919-555-1234",
    address: "5678 Elm St, Raleigh, NC 27601",
    notes: "This is a sample customer generated by the seeder",
  },
  {
    name: "Hidden Forces, LLC",
    email: "dk@hiddenforces.io",
    address: "33 IRVING PLACE, NEW YORK, NY, United States, 10003",
    phone: "+1 212-457-7333",
    notes: null,
  },
  {
    name: "Marketing Done Right, LLC",
    email: "dustin@marketingdr.co",
    phone: "+1 619-354-0355",
    address: "2165 Briarwood Rd. Cleveland Heights, OH 44118",
    notes: null,
  },
];

const seedCustomers = async () => {
  try {
    // Get all users from the database
    let users = await User.findAll();

    // If no users found, create a default user
    if (users.length === 0) {
      await User.create({
        firstName: "Default",
        lastName: "User",
        emailAddress: "default@example.com",
        password: "password",
      });

      // Retrieve all users again
      users = await User.findAll();
    }

    // Assign each customer to a random user
    const customerDataWithUsers = customerData.map((customer) => ({
      ...customer,
      userId: users[Math.floor(Math.random() * users.length)].id,
    }));

    // Seed invoices with the users associations
    await Customer.bulkCreate(customerDataWithUsers);
    console.log("Customers seeded successfully");
  } catch (error) {
    console.error("Error seeding customers:", error);
  }
};

module.exports = {
  up: seedCustomers,
};
